image: registry.gitlab.frielforreal.com/aelve/guide-build:latest

cache:
  untracked: true
  paths:
    - .stack-work

stages:
  - build

build:
  stage: build
  script:
    - stack build --install-ghc
