- ignore: {name: 'Redundant do'}
- ignore: {name: 'Redundant bracket'}
- ignore: {name: 'Redundant $'}
- ignore: {name: 'Redundant flip'}
- ignore: {name: 'Move brackets to avoid $'}
- ignore: {name: 'Eta reduce'}
- ignore: {name: 'Avoid lambda'}
- ignore: {name: 'Use camelCase'}
- ignore: {name: 'Use const'}
- ignore: {name: 'Use if'}
- ignore: {name: 'Use notElem'}
- ignore: {name: 'Use fromMaybe'}
- ignore: {name: 'Use maybe'}
- ignore: {name: 'Use fmap'}
- ignore: {name: 'Use foldl'}
- ignore: {name: 'Use :'}
- ignore: {name: 'Use ++'}
- ignore: {name: 'Use ||'}
- ignore: {name: 'Use &&'}
- ignore: {name: 'Use ?~'}
- ignore: {name: 'Use <$>'}
- ignore: {name: 'Use .'}
- ignore: {name: 'Use head'}
- ignore: {name: 'Use String'}
- ignore: {name: 'Use Foldable.forM_'}
- ignore: {name: 'Use newtype instead of data'}
- ignore: {name: 'Redundant lambda'}
- ignore: {name: 'Use section'}
