resolver: lts-8.13

packages:
- location: .
- location:
    git: https://github.com/aelve/stache-plus
    commit: 789aeabbf8069dec80647160f127d047e8f5a330
  extra-dep: true

extra-deps:
- cmark-sections-0.1.0.3
- patches-vector-0.1.5.4
- fmt-0.2.0.0
