resolver: lts-13.26

packages:
- back/

nix:
  shell-file: shell.nix

extra-deps:
- Spock-0.13.0.0
- Spock-core-0.13.0.0
- Spock-digestive-0.3.0.0
- digestive-functors-0.8.4.0
- Spock-lucid-0.4.0.1
- reroute-0.5.0.0
- cmark-0.5.6
- fmt-0.6
- cmark-sections-0.3.0.1
- acid-state-0.14.3
- stm-containers-0.2.16
- lzma-clib-5.2.2
- regex-1.0.1.5
- webdriver-0.9.0.1

# Not on Stackage
- to-1.0.0

# We want the newest hasql just because
- hasql-1.4
- hasql-transaction-0.7.2
- postgresql-binary-0.12.1.3

# Old versions from LTS 12+ (can and should be upgraded)
- megaparsec-6.5.0
- servant-0.15
- servant-server-0.15

# Older version due to megaparsec
- neat-interpolation-0.3.2.2

# Older version due to stm-containers
- focus-0.1.5.2

# We pin the precise versions of 'highlighting-kate' and 'cmark-highlight'
# because the frontend has copied a stylesheet from 'highlighting-kate'. If
# the version changes, we also have to update the stylesheet on the
# frontend. (See App.vue, or just grep for things like "span.st".)
- highlighting-kate-0.6.4
- cmark-highlight-0.2.0.0

# The new version of 'di' has different 'throw' semantics; we don't use it
# yet but let's not create technical debt for ourselves.
- di-1.2
- di-monad-1.3
- di-core-1.0.3
- df1-0.3.1
- di-df1-1.0.2
- di-handle-1.0.1

- git: https://github.com/aelve/stache-plus
  commit: 4c40c1297873cd5bb24a4aeb7c59b7a7f67ca671

- git: https://github.com/aelve/safecopy-migrate
  commit: 3971922c75ce2ca751b3da1653fefa109b746e21

# Fork of 'servant-swagger' with some changes (see its README)
- git: https://github.com/aelve/servant-swagger
  commit: ea54349ffbe474c70601b6d1f7f71535b77c73ae

# Fork of 'hspec-webdriver' that builds
- git: https://github.com/neongreen/webdriver-utils
  commit: db4a9027e62550c9d27110f36ae26c712acfbe95
  subdirs:
  - hspec-webdriver

# Fork of 'patches-vector' that builds
- git: https://github.com/neongreen/patches-vector
  commit: 9bb704cf7f14cff9ef76a5d177e4e56ceee24705
