name: guide
version: '1.0.0'
synopsis: An advanced wiki engine
description: An advanced wiki engine powering <guide.aelve.com>.

category: Web
author: Aelve
maintainer: artyom@aelve.com
license: BSD3

homepage: https://github.com/aelve/guide
git: git://github.com/aelve/guide.git
bug-reports: https://github.com/aelve/guide/issues

ghc-options:
- -Wall
- -Wno-unused-do-bind
- -Wmissing-export-lists
# https://github.com/commercialhaskell/stack/issues/3918
- -optP-Wno-nonportable-include-path

library:
  source-dirs: src
  default-extensions:
  - MultiWayIf
  - ViewPatterns
  - RecordWildCards
  - TupleSections
  - LambdaCase
  - RankNTypes
  - MultiParamTypeClasses
  - FunctionalDependencies
  - DeriveFunctor
  - DeriveTraversable
  - DeriveGeneric
  - TypeApplications
  - NoImplicitPrelude
  - ConstraintKinds
  - InstanceSigs
  - DerivingStrategies
  - TemplateHaskellQuotes
  - ScopedTypeVariables
  dependencies:
  - acid-state
  - aeson
  - aeson-pretty
  - async
  - base <5
  - base-prelude
  - bytestring
  - cereal
  - cmark ==0.5.*
  - cmark-highlight ==0.2.*
  - cmark-sections ==0.3.*
  - containers >=0.5
  - contravariant
  - data-default >=0.5
  - deepseq >=1.2.0.0
  - df1
  - di
  - di-core
  - di-monad
  - digestive-functors
  - directory >=1.2
  - exceptions
  - extra
  - feed ==1.0.*
  - filemanip ==0.3.6.*
  - filepath
  - fmt
  - friendly-time ==0.4.*
  - generics-eot
  - gitrev
  - hashable
  - hasql
  - hasql-transaction
  - http-api-data
  - http-client
  - http-client-tls
  - http-types
  - hvect
  - ilist
  - insert-ordered-containers
  - iproute ==1.7.*
  - lucid >=2.9.5 && <3
  - megaparsec ==6.*
  - microlens
  - microlens-platform >=0.3.2
  - mmorph ==1.*
  - mtl >=2.1.1
  - named
  - neat-interpolation ==0.3.*
  - network
  - network-uri
  - optparse-applicative
  - patches-vector
  - profunctors
  - random >=1.1
  - raw-strings-qq
  - reroute
  - safe
  - safecopy
  - safecopy-migrate ==0.2.*
  - say
  - scrypt
  - servant
  - servant-server
  - servant-swagger
  - servant-swagger-ui
  - shortcut-links >=0.4.2
  - signal
  - split
  - Spock
  - Spock-digestive
  - Spock-lucid
  - stache-plus ==0.1.*
  - swagger2
  - template-haskell
  - text
  - th-abstraction
  - time >=1.5
  - to
  - transformers
  - uniplate
  - utf8-string
  - vector
  - wai
  - wai-cors
  - wai-middleware-static
  - warp
  - xml-conduit
  - xml-types
  - xss-sanitize

executables:
  guide:
    main: Main.hs
    source-dirs: src/site
    ghc-options:
    - -threaded
    # See https://github.com/sol/hpack/issues/182#issuecomment-310434881 for
    # the explanation of the quoting situation here.
    - '"-with-rtsopts=-T -N"'
    dependencies:
    - base
    - guide

tests:
  tests:
    main: Main.hs
    source-dirs: tests
    default-extensions:
    - MultiWayIf
    - ViewPatterns
    - RecordWildCards
    - TupleSections
    - LambdaCase
    - RankNTypes
    - MultiParamTypeClasses
    - FunctionalDependencies
    - DeriveFunctor
    - DeriveTraversable
    - DeriveGeneric
    dependencies:
    - QuickCheck <3
    - aeson
    - async
    - base <5
    - bytestring
    - cmark
    - cmark-sections
    - containers
    - directory
    - exceptions
    - guide
    - hspec <3
    - hspec-expectations
    - hspec-webdriver <1.3
    - http-client
    - http-conduit
    - http-types
    - lucid <3
    - monad-loops <0.5
    - network-uri
    - quickcheck-text <0.2
    - regex
    - tagsoup <1
    - text
    - temporary
    - webdriver
    - yaml
